/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme/tesla.theme.ts
 * Command: astryx theme build app/theme/tesla.theme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const teslaTheme: DefinedTheme;
